- hosts: all
  gather_facts: false
  vars_files:
    - group_vars/webservers/vars.yml
    - group_vars/webservers/vault.yml
  tasks:
    - community.docker.docker_login:
        username: "{{ docker_login }}"
        password: "{{ docker_password }}"
    - community.docker.docker_container:
        name: devops-example-app
        image: "{{ docker_login }}/devops-example-app"
        published_ports:
          - 3000:3000
  roles:
    - { role: datadog.datadog, become: yes }
  vars:
    datadog_checks:
      process:
        init_config:
        instances:
          - name: Check website
            url: https://project77.home-cooking.ru/
