- hosts: all
  gather_facts: no
  tasks:
    - name: Install packages
      apt:
        name: python3-pip
        update_cache: yes

    - name: Install Docker
      pip:
        name: docker

    - name: Run container
      community.docker.docker_container:
        name: devops-example-app
        image: ksv2005/devops-example-app
        published_ports: 3000:3000
        restart_policy: always
        restart: yes
        pull: yes
        env:
          SERVER_MESSAGE: "{{ ansible_default_ipv4.address }}"

  roles:
    - { role: datadog.datadog, become: yes }
  vars:
    datadog_checks:
      process:
        init_config:
        instances:
          - name: Check website
            url: https://project77.home-cooking.ru/
